name: Build and Deploy to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make Gradle wrapper executable
        working-directory: ./lambda
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ./lambda
        run: ./gradlew build

      - name: Upload Lambda JAR
        uses: actions/upload-artifact@v4
        with:
          name: lambda-jar
          path: ./lambda/build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download Lambda JAR
        uses: actions/download-artifact@v4
        with:
          name: lambda-jar
          path: ./lambda/build/libs/

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform Init
        working-directory: ./infrastructure
        run: terraform init


      - name: Find JAR and Apply Terraform
        working-directory: ./infrastructure
        run: |
          JAR_PATH=$(ls ../lambda/build/libs/*.jar | head -n 1)
          echo "Using JAR: $JAR_PATH"
          terraform apply -auto-approve -var="lambda_package_path=$JAR_PATH"
